title: Services

options: 
  delete: false
  status: false
  duplicate: false
  url: false
  preview: "{{ site.url }}/#{{ page.slug }}"

tabs:
  content: 
    label:
      en: Content 
      fr: Contenu
    icon: text
    columns:
      left:
        width: 2/3 
        fields:
          headline: fields/headline  
    
          headlineintro: fields/intro
    
          textcontent:
            label: Sections 
            type: structure
            columns: 
             titlesection:
                width: 1/3
             size:
                width: 1/3
             onhome:
                width: 1/3
    
            fields:    
              onhome: 
                label: 
                  en: On home?
                  fr: Accueil?
                type: toggle


    
              titlesection: fields/structurekt/sectiontitle  
    
              size: fields/structurekt/size

              # Unfortunatly, editor won't work here even with pretty to false :(
              # onhomecontent: 
              #   label: 
              #     en: Custom introduction
              #     fr: Introduction personnalisée
              #   type: editor 
              #   pretty: false
              #   when: 
              #     onhome: true
              #   help:
              #     en: The content of this field will be displayed with formatted text. If empty, an unformatted excerpt from section content will be used.
              #     fr: Le contenu de ce champs sera affiché avec du texte formaté sur la page d'accueil. S'il reste vide, un extrait non formaté   du contenu de la section sera utilisé.

              onhomecontent: 
                label: 
                  en: Text
                  fr: Texte
                type: textarea 
                buttons: 
                  - bold
                  - italic
                  - '|'
                  - link
                  - email
                  - file
    
             
              linelink:
                type: line     
              itemlink: fields/linkfieldmaster

      right:
        width: 1/3 
        sections:
          images:
            type: files
            template: gallery
             
      
  # homesettings
  homesettings:
    label: 
      en: Settings
      fr: Paramètres
    icon: settings
    fields:
      hideServices:
        label:
          en: Show section?
          fr: Afficher la section?
        type: toggle